format = """
[](#FF8800)\
$os\
[](bg:#FFFFFF fg:#FF8800)\
$username\
[](bg:#44AACC fg:#FFFFFF)\
$directory\
[](bg:#444444 fg:#44AACC)\
$git_branch\
$git_status\
[ ](fg:#444444)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#FFFFFF fg:#202020"
style_root = "bg:#FFFFFF"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#FF8800 fg:#FFFFFF"
format = '[ $name ]($style)'
disabled = false # Disabled by default

[directory]
style = "bg:#44AACC fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "bg:#444444"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#444444"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
